/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JOpusFile */

#ifndef _Included_JOpusFile
#define _Included_JOpusFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JOpusFile
 * Method:    jopusOpenFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JOpusFile_jopusOpenFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JOpusFile
 * Method:    jopusRead
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_JOpusFile_jopusRead
  (JNIEnv *, jobject, jobject);

/*
 * Class:     JOpusFile
 * Method:    jopusClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JOpusFile_jopusClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
