/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glester_jopus_JOpusDecodable */

#ifndef _Included_com_glester_jopus_JOpusDecodable
#define _Included_com_glester_jopus_JOpusDecodable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glester_jopus_JOpusDecodable
 * Method:    jopusRead
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_glester_jopus_JOpusDecodable_jopusRead
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_glester_jopus_JOpusDecodable
 * Method:    jopusClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glester_jopus_JOpusDecodable_jopusClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
