/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glester_jopus_JOpusFile */

#ifndef _Included_com_glester_jopus_JOpusFile
#define _Included_com_glester_jopus_JOpusFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glester_jopus_JOpusFile
 * Method:    jopusOpenFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_glester_jopus_JOpusFile_jopusOpenFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
