/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glester_jopus_JOpusBufferFile */

#ifndef _Included_com_glester_jopus_JOpusBufferFile
#define _Included_com_glester_jopus_JOpusBufferFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glester_jopus_JOpusBufferFile
 * Method:    jopusOpenMemory
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_glester_jopus_JOpusBufferFile_jopusOpenMemory
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_glester_jopus_JOpusBufferFile
 * Method:    jopusReadMemory
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_glester_jopus_JOpusBufferFile_jopusReadMemory
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_glester_jopus_JOpusBufferFile
 * Method:    jopusCloseMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_glester_jopus_JOpusBufferFile_jopusCloseMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
